module.exports = [
  // {
  //   type: 'text-input',
  //   icon: 'xxx',
  //   options: {
  //     key: '',
  //     label: '文本',
  //     width: '',
  //     hidden: false,
  //     placeholder: '你好1 ',
  //     defaultValue: '',
  //     customClass: '',
  //     required: true,
  //   },
  // },
  // {
  //   type: 'text-input',
  //   icon: 'xxx',
  //   options: {
  //     key: '',
  //     label: '文本',
  //     width: '50%',
  //     hidden: true,
  //     placeholder: '2222',
  //     defaultValue: '3333',
  //     customClass: '',
  //   },
  // },
  // {
  //   type: 'text-input',
  //   icon: 'xxx',
  //   options: {
  //     textarea: true,
  //     key: '',
  //     label: '文本',
  //     width: '50%',
  //     hidden: true,
  //     placeholder: '2222',
  //     defaultValue: '3333',
  //     customClass: '',
  //     textarea: true,
  //   },
  // },
  // {
  //   type: 'html-code',
  //   icon: 'xxx',
  //   options: {
  //     key: '',
  //     label: 'html 块',
  //     hidden: false,
  //     customClass: '',
  //     htmlCode: '<span style="color:red;">111</span>',
  //   },
  // },
];
